UKHomeOffice/cop-react-components

- packages/components/src/Details/Details.jsx
- packages/components/src/Details/Details.scss
- packages/components/src/Details/Details.stories.mdx
- packages/components/src/Details/Details.test.js
- packages/components/src/Details/index.js
- packages/components/src/index.js
Added the `Details` component, along with unit tests and a Storybook story.
This PR depends on the following PR and should be rebased against `master` before it eventually gets merged:
> COP-9149: Add Details component

- packages/components/src/Tag/Tag.jsx
- packages/components/src/Tag/Tag.scss
- packages/components/src/Tag/Tag.stories.mdx
- packages/components/src/Tag/Tag.stories.scss
- packages/components/src/Tag/Tag.test.js
- packages/components/src/Tag/index.js
- packages/components/src/index.js
Added the `Tag` component, along with unit tests and a Storybook story.
The styling has also been overridden from the GDS standard so that the text displays in sentence case, rather than capitalised.
Instructions to see the components within Storybook are …
> COP-9142: Add Tag component

- packages/components/src/InsetText/InsetText.jsx
- packages/components/src/InsetText/InsetText.scss
- packages/components/src/InsetText/InsetText.stories.mdx
- packages/components/src/InsetText/InsetText.test.js
- packages/components/src/InsetText/index.js
- packages/components/src/index.js
Added the `InsetText` component, along with unit tests and Storybook stories.
* …
> COP-9037: Add InsetText component

- packages/components/src/TextInput/TextInput.jsx
- packages/components/src/TextInput/TextInput.scss
- packages/components/src/TextInput/TextInput.stories.mdx
- packages/components/src/TextInput/TextInput.test.js
- packages/components/src/TextInput/index.js
- packages/components/src/index.js
Added the `TextInput` component, along with unit tests and Storybook stories.
* …
> COP-8969: Add TextInput component

- packages/components/src/Alert/Alert.jsx
- packages/components/src/Alert/Alert.scss
- packages/components/src/Alert/Alert.stories.mdx
- packages/components/src/Alert/Alert.test.js
- packages/components/src/Alert/index.js
- packages/components/src/index.js
Added the `Alert` component, along with unit tests and Storybook stories.
* https://github.com/UKHomeOffice/cop-react-design-system/pull/7
Instructions to see the components within Storybook are in the `README.md` files, but the TLDR version is to run the …
> COP-9039: Add Alert component

- packages/components/src/Label/Label.jsx
- packages/components/src/Label/Label.scss
- packages/components/src/Label/Label.stories.mdx
- packages/components/src/Label/Label.test.js
- packages/components/src/Label/index.js
- packages/components/src/index.js
Added the `Label` component, along with unit tests and Storybook stories.
* https://github.com/UKHomeOffice/cop-react-design-system/pull/5
Instructions to see the components within Storybook are in the `README.md` files, but the TLDR version is to run the …
> COP-9138: Add Label component

- packages/components/src/Hint/Hint.jsx
- packages/components/src/Hint/Hint.scss
- packages/components/src/Hint/Hint.stories.mdx
- packages/components/src/Hint/Hint.test.js
- packages/components/src/Hint/index.js
- packages/components/src/index.js
Added the `Hint` component, along with unit tests and Storybook stories.
* https://github.com/UKHomeOffice/cop-react-design-system/pull/5
Instructions to see the components within Storybook are in the `README.md` files, but the TLDR version is to run the …
> COP-9134: Add Hint component

- packages/components/src/VisuallyHidden/VisuallyHidden.jsx
- packages/components/src/VisuallyHidden/VisuallyHidden.scss
- packages/components/src/VisuallyHidden/VisuallyHidden.stories.mdx
- packages/components/src/VisuallyHidden/VisuallyHidden.stories.scss
- packages/components/src/VisuallyHidden/VisuallyHidden.test.js
- packages/components/src/VisuallyHidden/index.js
- packages/components/src/index.js
Added the `VisuallyHidden` component, along with unit tests and a Storybook story.
* https://github.com/UKHomeOffice/cop-react-design-system/pull/5
Instructions to see the components within Storybook are in the `README.md` files, but the TLDR version is to …
> COP-9141: Add VisuallyHidden component

- packages/components/src/ErrorMessage/ErrorMessage.jsx
- packages/components/src/ErrorMessage/ErrorMessage.scss
- packages/components/src/ErrorMessage/ErrorMessage.stories.mdx
- packages/components/src/ErrorMessage/ErrorMessage.test.js
- packages/components/src/ErrorMessage/index.js
- packages/components/src/index.js
Added the `ErrorMessage` component, along with unit tests and a Storybook story.
* https://github.com/UKHomeOffice/cop-react-design-system/pull/5
* https://github.com/UKHomeOffice/cop-react-design-system/pull/12
Instructions to see the components within …
> COP-9040: Add ErrorMessage component

- packages/components/src/Button/Button.jsx
- packages/components/src/Button/Button.scss
- packages/components/src/Button/Button.stories.mdx
- packages/components/src/Button/Button.test.js
- packages/components/src/Button/index.js
- packages/components/src/ButtonGroup/ButtonGroup.jsx
- packages/components/src/ButtonGroup/ButtonGroup.scss
- packages/components/src/ButtonGroup/ButtonGroup.stories.mdx
- packages/components/src/ButtonGroup/ButtonGroup.stories.scss
- packages/components/src/ButtonGroup/ButtonGroup.test.js
- packages/components/src/ButtonGroup/index.js
- packages/components/src/Link/Link.jsx
- packages/components/src/Link/Link.scss
- packages/components/src/Link/Link.test.js
- packages/components/src/Link/index.js
- packages/components/src/index.js
Added the `Button` and `ButtonGroup` components, as well as a basic `Link` component, along with unit tests and Storybook stories.
Instructions to see the components within Storybook are in the `README.md` files, but the TLDR version is to run the following …
> COP-9036: Add Button, ButtonGroup, and Link components

- packages/components/src/FormGroup/FormGroup.jsx
- packages/components/src/FormGroup/FormGroup.scss
- packages/components/src/FormGroup/FormGroup.stories.mdx
- packages/components/src/FormGroup/FormGroup.test.js
- packages/components/src/FormGroup/index.js
- packages/components/src/index.js
Added the `FormGroup` component, along with unit tests and Storybook stories.
> COP-9143: Add FormGroup component

- packages/components/package.json
- packages/components/yarn.lock
Added a resolution to `package.json` for `immer` version `9.0.6`. Since this uses yarn for compilation, it should simply work.
As described, this addresses a security issue with versions of `immer` earlier than `9.0.6`. This should now build and deploy correctly without the npm audit failing.
> COP-9233: Override immer version

- packages/components/src/Radios/Radio.jsx
- packages/components/src/Radios/Radio.test.js
- packages/components/src/Radios/Radios.jsx
- packages/components/src/Radios/Radios.scss
- packages/components/src/Radios/Radios.stories.mdx
- packages/components/src/Radios/Radios.test.js
- packages/components/src/Radios/index.js
- packages/components/src/index.js
Added the `Radios` component (and accompanying `Radio` component), along with unit tests and Storybook stories.
https://support.cop.homeoffice.gov.uk/browse/COP-8968
> COP-8968: Add Radios component

- .github/workflow/publish-cop-react-components-to-npm.yml
- .github/workflow/publish-to-npm.yml
Created a workflow for publishing the library to npm.
Check that the component library gets published to https://www.npmjs.com/package/@ukhomeoffice/cop-react-components and that it is public and not private. If so, this has succeeded.
> COP-9328: Create workflow for npm publish

- .github/workflows/publish-cop-react-components-to-npm.yml
- packages/components/package.json
The job needed to have a working-directory rather than navigating to the corresponding folder. It also seems that `yarn publish` doesn't work correctly for our needs as it prompts for the new version number.
> COP-9328: Fix npm publish workflow

- .github/workflows/deploy-storybook.yml
Added flags to deploy in CI mode, as per the documentation. This was previously failing at the deploy stage, citing invalid credentials, which is what this should address - hence the use of `GITHUB_TOKEN`.
Check that the Storybook for the component library gets published to https://ukhomeoffice.github.io/cop-react-components/. If so, this has succeeded.
> COP-9332: Deploy Storybook in CI mode

- .github/workflows/deploy-storybook.yml
Set the environment variable to be `GH_TOKEN`.
Check that the Storybook for the component library gets published to https://ukhomeoffice.github.io/cop-react-components/. If so, this has succeeded.
> COP-9332: Update workflow to use GH_TOKEN

- packages/components/src/Autocomplete/Autocomplete.jsx
- packages/components/src/Autocomplete/Autocomplete.stories.mdx
- packages/components/src/Readonly/Readonly.jsx
- packages/components/src/Readonly/Readonly.scss
- packages/components/src/Readonly/Readonly.stories.mdx
- packages/components/src/Readonly/Readonly.test.js
- packages/components/src/Readonly/index.js
- packages/components/src/TextInput/TextInput.jsx
- packages/components/src/TextInput/TextInput.stories.mdx
- packages/components/src/TextInput/TextInput.test.js
- packages/components/src/index.js
Added a Readonly component for use within otherwise editable components when they are in a readonly state. This is distinct from a "disabled" state.
https://support.cop.homeoffice.gov.uk/browse/COP-8970
Also added accompanying unit test and Storybook stories.
> COP-8970: Add Readonly component

- .github/workflows/build-and-test.yml
- packages/components/package.json
Set the version to 0.3.0 for a release.
Also removed the "push" trigger for the "Build and test" workflow so we don't get double runs when they're linked to a PR - it's enough to have it based on an attempt to merge.
> Set version to 0.3.0 for release

- packages/components/package.json
- packages/components/src/Heading/Heading.jsx
- packages/components/src/Heading/Heading.scss
- packages/components/src/Heading/Heading.stories.mdx
- packages/components/src/Heading/Heading.test.js
- packages/components/src/Heading/index.js
- packages/components/src/Markup/Markup.jsx
- packages/components/src/Markup/Markup.stories.mdx
- packages/components/src/Markup/Markup.test.js
- packages/components/src/Markup/index.js
- packages/components/src/index.js
- packages/components/yarn.lock
Added a `Markup` component, along with a specialised form of this in the `Heading` component.
Also added unit tests and Storybook stories for both.
https://support.cop.homeoffice.gov.uk/browse/COP-8972
> COP-8972: Add formatted text component

- packages/components/package.json
- packages/components/src/ErrorSummary/ErrorSummary.scss
- packages/components/src/Heading/Heading.scss
- packages/components/src/Radios/Radios.jsx
- packages/components/src/Radios/Radios.stories.mdx
- packages/components/src/Radios/Radios.test.js
Added an option to display the `Radios` component in a readonly format. This shows just the selected option as label text, which is distinct from a disabled component that shows all of the options in a disabled state.
This will most prominently be visible on the **Check your answers** screen where there is an underlying `Radios` component on the corresponding page/section.
> COP-9578: Readonly Radios component

- src/Autocomplete/Autocomplete.stories.mdx
- src/Autocomplete/Countries.stories.test.js
- src/FormGroup/FormGroup.stories.mdx
- src/Heading/Heading.jsx
- src/Heading/Heading.test.js
1. Renamed `Countries.stories.js` to `Countries.stories.test.js` and added a basic test to it so that the file, which is used _purely_ for Storybook stories doesn't feature in the coverage analysis.
2. Following conversation with UX team, the large Heading should be an `<h1 />` as it is quite rare that we will use an extra large heading and, semantically, there should always be an `<h1 />` on the page. The medium heading has therefore also moved up to be an `<h2 />`.
> Chore: code clean ups

- package.json
- src/TextArea/TextArea.jsx
- src/TextArea/TextArea.scss
- src/TextArea/TextArea.stories.mdx
- src/TextArea/TextArea.test.js
- src/TextArea/index.js
- src/assets/scss/storybook.css
- src/index.js
Added a `TextArea` component (initially as part of a demo). The Storybook stories are aligned with those on GDS (with adjustments and additions where appropriate) and the unit tests are quite extensive and sensible (100% coverage, catching all the edge cases I could think of).
https://support.cop.homeoffice.gov.uk/browse/COP-10048
Essentially covered by accompanying unit tests and Storybook stories.
> COP-10048: Add TextArea component

- package.json
- src/DateInput/DateInput.jsx
- src/DateInput/DateInput.stories.mdx
- src/DateInput/DateInput.test.js
- src/utils/Utils.js
The previous implementation of the Date component passed up values for each part of the date (day, month, year) to Form Renderer separately with property names in the format "ComponentID-Day", "ComponentID-Month" etc. The validators in Form Renderer then looked for a value to be assigned the property "ComponentID" and found none and validation didn't work properly. 
This change captures changes to each of the Date fields and consolidates them into a single string format "dd-mm-yyyy" before passing on that new information to Form Renderer with property name "ComponentID" so the validators can find the value and function properly. If any of the fields are empty then an empty string is returned instead meaning that if someone enters a day and a year leaving the month blank they will still be …
> EAB-105 Make required validation work for Date component

- .storybook/main.js
- package.json
- src/assets/scss/storybook.css
- yarn.lock
Work done by Ali Khattab and Keenan Batley to get everything compiling and playing nicely with the `yarn audit`, such that the only vulnerability issues are non-production ones (these will be addressed separately).
https://support.cop.homeoffice.gov.uk/browse/COP-10002
The build should work, Storybook should compile and run just fine (and look correct), and the following command should bring back no vulnerabilities:
`yarn audit --groups "dependencies"`
> COP-10002: Fix vulnerability issues

- .storybook/govuk-theme.js
- src/Details/Details.scss
- src/Link/Link.scss
Replacing the GDS blue with the Home Office blue. This is needed for the contrast ratio - the Home Office blue is slightly darker than the GDS one.
There should be no accessibility contrast issues with the `Link` or `Details` components, nor with any anchor tags, using an accessibility tool like Wave or Axe.
> Replace GDS blue with Home Office blue

- src/Checkboxes/Checkboxes.stories.mdx
- src/DateInput/DateInput.stories.mdx
- src/ErrorMessage/ErrorMessage.stories.mdx
- src/InsetText/InsetText.stories.mdx
- src/TextArea/TextArea.stories.mdx
- src/TextInput/TextInput.stories.mdx
- src/VisuallyHidden/VisuallyHidden.stories.mdx
Components that haven't yet been checked by UX and the test team should be given an `Alpha` tag in the corresponding Storybook story. I've added them for `Checkboxes`, `DateInput`, `TextArea`, and the updated `TextInput` that haven't yet gone through the sign-off process.
Also sorted out some of the names in the menu so that they're sentence case rather than Pascal case.
The `Checkboxes`, `DateInput`, `TextArea`, and `TextInput` components should each display an `Alpha` tag beneath the page title in Storybook.
> Tag alpha components

- src/Autocomplete/Autocomplete.stories.mdx
- src/Autocomplete/Countries-sb.js
- src/Autocomplete/Countries-sb.test.js
- src/FormGroup/FormGroup.stories.mdx
The Storybook story for the `Autocomplete` would _sometimes_ work fine and other times not. It seems to be related to trying to import a .test.js file in those stories so I've simply renamed the file for it and added a test to not drop coverage.
There should be a link for the `Autocomplete` component in the left-hand side and the page should render fine when it is clicked on. If there's no link or there's a problem with the page, this fails.
> Fix autocomplete story

- package.json
- src/Button/Button.jsx
- src/Button/Button.scss
- src/Button/Button.stories.mdx
- src/ButtonGroup/ButtonGroup.jsx
- src/ButtonGroup/ButtonGroup.scss
- src/ButtonGroup/ButtonGroup.stories.mdx
Introduced new `hods-button` and `hods-button-group` classes for the `Button` and `ButtonGroup` components, respectively. They each extend the corresponding `govuk` classes and override some of the colours, borders, and shadows, according to the Figma designs.
There was no `'warning'` button that I could find so that remains the same as the GDS one.
https://support.cop.homeoffice.gov.uk/browse/COP-10269
The button colours should now be aligned to those in the Figma document linked to in the JIRA ticket. Also make sure the layouts haven't changed and that the buttons are appropriately lined up with the same height, etc.
> COP-10269: Use hods-button class instead

- package.json
- src/Autocomplete/Autocomplete.stories.mdx
The `Autocomplete` story should reuse the components within the library, rather than mark a bunch of things up with class names.
> Use Button components in Autocomplete story

- package.json
- src/Button/Button.scss
- src/ButtonGroup/ButtonGroup.scss
The margin for buttons in the mobile view is such that the buttons end up getting pushed off to the left. This needs to be sorted or else it looks odd in the mobile view.
https://support.cop.homeoffice.gov.uk/browse/COP-10358
The spacing between buttons should look correct on the desktop and tablet views. When viewing on a mobile, they should now also look correct and not offset to the left, which is how they _were_ appearing.
> COP-10358: Fix button margins

- package.json
- src/Tag/Tag.scss
- src/Tag/Tag.stories.mdx
Description
Added a `dark-grey` colour to the `Tag` component for increased contrast. Added a row in the Tag story table with an example.
https://support.cop.homeoffice.gov.uk/browse/COP-10589
> added a dark-grey colour in the tag component

- package.json
- src/FileUpload/FileUpload.jsx
- src/FileUpload/FileUpload.scss
- src/FileUpload/FileUpload.stories.mdx
- src/FileUpload/FileUpload.test.js
- src/FileUpload/index.js
- src/index.js
Added a `FileUpload` component, which presently accepts a single file at a for upload and displays a thumbnail of the selected file if it's an or otherwise "displays" an icon for the file type. The icon itself is outside the scope of this component, however, but allows application developers to override the `document-icon-{extension}` class with an appropriate style and background image.
https://support.cop.homeoffice.gov.uk/browse/COP-10567
Covered by accompanying unit tests and Storybook stories.
> COP-10567: Add FileUpload component

- package.json
- src/Checkboxes/Checkboxes.jsx
- src/Checkboxes/Checkboxes.test.js
- src/Radios/Radios.jsx
- src/Radios/Radios.test.js
The IDs for the options within `Radios` and `Checkboxes` were not unique across the form. They now are.
https://support.cop.homeoffice.gov.uk/browse/COP-10935
Accompanying unit tests have been updated. To test this in practice, you need to see it within a `container` or `collection` in the COP React Form Renderer.
> COP-10935: Fix uniqueness of option IDs

- package.json
- src/DateInput/DateInput.jsx
- src/DateInput/DateInput.test.js
Fixes an issue where changing the `value` externally results in an endless loop.
https://support.cop.homeoffice.gov.uk/browse/COP-10967
Covered by unit tests. However, you can see the broken behaviour in the COP React Form Renderer with the following steps:
1. Set up the JSON to have a date field;
2. Set up the initial data to have a valid value for that date field;
3. Switch to the Preview tab and you'll see the value appropriately showing in the date field;
4. Go back to the initial date and change to another valid value for the date field;
5. Switch back to the Preview tab and you'll now see the value in the date field flicking between the old and new values.
This has been fixed but until this has been merged and published to npm, it will continue to be broken in the Form Renderer. …
> COP-10967: Fix DateInput

- package.json
- src/Radios/Radio.jsx
- src/Radios/Radio.test.js
- src/Radios/Radios.jsx
- src/Radios/Radios.stories.mdx
The onChange function within the radios component was submitting all changes it caught with the fieldId of the Radios component, this meant that changes to nested components were being caught and also passed up as changes with the Radios fieldId. The value for the Radios component was then set to the value of the nested component. 
Collections have component names like `people[0].title` where as things outside of collections would just have names like `title`. This PR deconstructs the collection names to extract the original fieldId and then only calls onChange if the change has actually originated from the Radios component. Changes to the nested component are passed up by their own onChange handlers.
> Update onchange for radios to handle nested components and collections

- package.json
When this library was being consumed by something else, it required the something else to set up `react-select` as a dependency or it would fail.
> Add react-select to dependencies

- package.json
- src/TimeInput/TimeInput.jsx
- src/TimeInput/TimeInput.test.js
Fixes an issue where changing the `value` externally results in an endless loop. This was already fixed for the `DateInput` in a similar way.
https://support.cop.homeoffice.gov.uk/browse/COP-10967
Covered by unit tests. However, you can see the broken behaviour in the COP React Form Renderer with the following steps:
1. Set up the JSON to have a time field;
2. Set up the initial data to have a valid value for that time field;
3. Switch to the Preview tab and you'll see the value appropriately showing in the time field;
4. Go back to the initial time and change to another valid value for the time field;
5. Switch back to the Preview tab and you'll now see the value in the time field flicking between the old and new values.
This has been fixed but until this has been merged and published to …
> COP-10967: Fix TimeInput

- package.json
- src/FileUpload/FileUpload.jsx
Fixed an issue with a nested file upload where the label's `htmlFor` didn't match the name of the file input so clicking on it did nothing.
> Fix issue with nested file upload

- package.json
- src/Button/Button.scss
A bugfix, to replace the green button font from GDS Transport to Roboto.
[link_to_jira_story](https://support.cop.homeoffice.gov.uk/browse/COP-11028)
> Cop 11028/change button font to gds transport

- package.json
- src/Checkboxes/Checkboxes.jsx
- src/Checkboxes/Checkboxes.stories.mdx
- src/Checkboxes/Checkboxes.test.js
This update enables the following two features:
Allows you to add a divider as a string to separate checkboxes
Enables the user to select an 'exclusive' checkbox which, when selected, deselects all other checkboxes. Upon re-selecting any other checkbox, this 'exclusive' checkbox deselects.
This is mainly to enable the use of a 'None of the above' checkbox but can have other applications. This is done by adding the 'behaviour' field with the value of 'exclusive' for the necessary option(s) as shown below:
`{ 
value: 'citizen-of-another-country',
label: 'Citizen Of Another Country',
behaviour: 'exclusive'
}`
An extra checkboxes example has been added to the bottom of the checkboxes.stories.mdx file
1. Run yarn storybook
2. Navigate to Checkboxes
3. Scroll to the 'Checkbox items with …
> Added functionality for exclusive checkboxes

- package.json
- src/Autocomplete/Autocomplete.jsx
- src/Autocomplete/Autocomplete.scss
This enables the autocomplete component to be configured to act like a select component - allowing the user to select an option using the mouse. This functionality already existed in the Accessible Autocomplete that our autocomplete component wraps, it just needed exposing so it could be configured in Form Renderer JSON files.
To test this functionality, there are now two extra options that can be set within a Form Renderer JSON file when defining an autocomplete component:
```
"showAllValues": true,
```
This option will display a select-style list of all options available as soon as the autocomplete is focused. A user can either select a value from this list, or begin typing to filter the list just as in a standard autocomplete field. Setting this option to `true` will render the …
> EAB-583 Enabled autocomplete to use select functionality
